# Generated by Django 5.2.6 on 2025-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('membership_number', models.CharField(max_length=50, null=True, unique=True)),
                ('membership_type', models.CharField(choices=[('standard', 'Standard'), ('minor', 'Minor'), ('counselor', 'Counselor')], default='standard', max_length=20, verbose_name='Membership type')),
                ('joined_date', models.DateField(auto_now_add=True, null=True)),
                ('renewal_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('expiration_date', models.DateField()),
                ('address_street', models.CharField(max_length=255, verbose_name='Address street')),
                ('address_number', models.CharField(max_length=10, verbose_name='Address number')),
                ('address_city', models.CharField(max_length=100, verbose_name='Address city')),
                ('address_zip', models.CharField(max_length=20, verbose_name='Address ZIP code')),
                ('address_province', models.CharField(max_length=100, verbose_name='Address province')),
                ('address_country', models.CharField(max_length=100, null=True, verbose_name='Address country')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('birth_city', models.CharField(max_length=100, verbose_name='Birth city')),
                ('birth_province', models.CharField(max_length=100, verbose_name='Birth province')),
                ('birth_country', models.CharField(max_length=100, null=True, verbose_name='Birth country')),
                ('fiscal_code', models.CharField(max_length=50, null=True, unique=True, verbose_name='Fiscal code')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('card_sent', models.BooleanField(default=False, verbose_name='Card sent')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('parent_email', models.EmailField(max_length=254, null=True, verbose_name='Parent email')),
                ('privacy_accepted', models.BooleanField(default=False, verbose_name='Accepted privacy policy')),
            ],
        ),
    ]
