# Generated by Django 5.2.6 on 2025-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0002_alter_associate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='fiscal_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Fiscal code'),
        ),
    ]
