# Generated by Django 5.2.6 on 2025-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0003_alter_associate_fiscal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent email'),
        ),
    ]
