# Generated by Django 5.2.6 on 2025-11-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0004_alter_associate_parent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fiscal code'),
        ),
    ]
