# Generated by Django 5.2.6 on 2026-01-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0005_alter_associate_fiscal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address country'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='address_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address province'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='birth_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birth country'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='birth_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birth province'),
        ),
    ]
