services:
  web:
    build: .
    ports:
      - "8000:8000"    
    depends_on:
      - db
    env_file: ./app/.env
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ski_club
      PGDATA: /var/lib/postgresql/data/pgdata 	
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data 