import datetime

from django.test import TestCase

from apps.associates.models import Associate


class AssociateModelTests(TestCase):
    def setUp(self):
        self.associate = Associate.objects.create(
            first_name="Alice",
            last_name="Smith",
            email="alice@example.com",
            membership_number="12345",
            expiration_date=datetime.date(2025, 8, 31),
            address_street="Main Street",
            address_number="42",
            address_city="New York",
            address_zip="10001",
            address_province="NY",
            address_country="USA",
            birth_date=datetime.date(2000, 1, 1),
            birth_city="Los Angeles",
            birth_province="CA",
            birth_country="USA",
            fiscal_code="ABC123XYZ",
            parent_email="parent@example.com",
        )

    def test_str_method(self):
        self.assertEqual(str(self.associate), "Alice Smith")

    def test_membership_number_autogenerated(self):
        associate = Associate.objects.create(
            first_name="Bob",
            last_name="Jones",
            email="bob@example.com",
            expiration_date=datetime.date(2025, 8, 31),
            address_street="Second Street",
            address_number="10",
            address_city="Boston",
            address_zip="02118",
            address_province="MA",
            address_country="USA",
            birth_date=datetime.date(2010, 5, 5),
            birth_city="Boston",
            birth_province="MA",
            birth_country="USA",
            fiscal_code="XYZ789ABC",
            parent_email="parent2@example.com",
        )
        self.assertIsNotNone(associate.membership_number)
        self.assertEqual(len(associate.membership_number), 8)
