# Generated by Django 5.2.6 on 2025-09-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '__first__'),
        ('associates', '0001_initial'),
        ('transactions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.DateField()),
                ('certification_exp_date', models.DateField(blank=True, null=True)),
                ('certification_file', models.FileField(blank=True, null=True, upload_to='subscription_certifications/')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_subscription', to='articles.article')),
                ('associate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associate_subscription', to='associates.associate')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_subscription', to='transactions.transaction')),
                ('transaction_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactionline_subscription', to='transactions.transactionline')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('associate', 'article'), name='unique_subscription_per_associate_article')],
            },
        ),
    ]
