# Generated by Django 5.2.6 on 2026-09-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0004_alter_article_category"),
        ("associates", "0006_alter_associate_address_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkipassUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Ski day")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skipass_usages",
                        to="articles.article",
                    ),
                ),
                (
                    "associate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skipass_usages",
                        to="associates.associate",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "associate"),
                        name="unique_skipass_usage_per_day",
                    )
                ],
            },
        ),
    ]
