# Generated by Django 5.2.6 on 2025-09-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '__first__'),
        ('associates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount')),
                ('transaction_type', models.CharField(default='', verbose_name='Type')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='associates.associate')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='articles.article')),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associates.associate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.transaction')),
            ],
        ),
    ]
