# Generated by Django 5.2.6 on 2025-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('wiretransfer', 'Wire Transfer'), ('card', 'Card (POS)')], default='cash', max_length=20, verbose_name='Payment Method'),
        ),
    ]
