# Generated by Django 5.2.6 on 2026-01-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
