# Generated by Django 5.2.6 on 2026-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transactionline_line_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionline",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantity"),
        ),
    ]
