# Generated by Django 5.2.6 on 2026-09-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("associates", "0006_alter_associate_address_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("date", models.DateField(verbose_name="Date")),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("ended", "Ended"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ContestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Number"
                    ),
                ),
                (
                    "race_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Race time"
                    ),
                ),
                (
                    "associate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_participations",
                        to="associates.associate",
                    ),
                ),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="contests.contest",
                    ),
                ),
            ],
            options={
                "ordering": ["number", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contest", "associate"),
                        name="unique_participant_per_contest",
                    ),
                    models.UniqueConstraint(
                        fields=("contest", "number"), name="unique_number_per_contest"
                    ),
                ],
            },
        ),
    ]
