# Generated by Django 5.2.6 on 2025-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('certification_required', models.BooleanField(default=False, verbose_name='Medical cert. req.')),
                ('type', models.CharField(choices=[('course', 'Course'), ('single', 'Single')], default='single', max_length=20, verbose_name='Type')),
            ],
        ),
    ]
