# Generated by Django 5.2.6 on 2025-10-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('gymnastics', 'Gymnastics'), ('skischool', 'Ski school'), ('membership', 'Membership fee'), ('tripfee', 'Trip fee')], default='membership', max_length=20, verbose_name='Category'),
        ),
    ]
