# Generated by Django 5.2.6 on 2025-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('gymnastics', 'Gymnastics'), ('skischool', 'Ski school'), ('membership', 'Membership fee'), ('tripfee', 'Trip fee'), ('discount', 'Discount')], default='membership', max_length=20, verbose_name='Category'),
        ),
    ]
